export const SELECT_LOGIN_REQUEST = 'SELECT_LOGIN_REQUEST';
export const SELECT_LOGIN_SUCCESS = 'SELECT_LOGIN_SUCCESS';
export const SELECT_LOGIN_FAILURE = 'SELECT_LOGIN_FAILURE';

export const INSERT_HOUSE_REQUEST = 'INSERT_HOUSE_REQUEST';
export const INSERT_HOUSE_SUCCESS = 'INSERT_HOUSE_SUCCESS';
export const INSERT_HOUSE_FAILURE = 'INSERT_HOUSE_FAILURE';

export const DELETE_HOUSE_REQUEST = 'DELETE_HOUSE_REQUEST';
export const DELETE_HOUSE_SUCCESS = 'DELETE_HOUSE_SUCCESS';
export const DELETE_HOUSE_FAILURE = 'DELETE_HOUSE_FAILURE';

export const UPDATE_HOUSE_REQUEST = 'UPDATE_HOUSE_REQUEST';
export const UPDATE_HOUSE_SUCCESS = 'UPDATE_HOUSE_SUCCESS';
export const UPDATE_HOUSE_FAILURE = 'UPDATE_HOUSE_FAILURE';

export const INSERT_IMAGE_REQUEST = 'INSERT_IMAGE_REQUEST';
export const INSERT_IMAGE_SUCCESS = 'INSERT_IMAGE_SUCCESS';
export const INSERT_IMAGE_FAILURE = 'INSERT_IMAGE_FAILURE';

export const SELECT_HOUSE_REQUEST = 'SELECT_HOUSE_REQUEST';
export const SELECT_HOUSE_SUCCESS = 'SELECT_HOUSE_SUCCESS';
export const SELECT_HOUSE_FAILURE = 'SELECT_HOUSE_FAILURE';
export const INSERT_HOUSE_REPLACE = 'INSERT_HOUSE_REPLACE';
export const DELETE_HOUSE_REPLACE = 'DELETE_HOUSE_REPLACE';
export const UPDATE_HOUSE_REPLACE = 'UPDATE_HOUSE_REPLACE';
export const RESET_SELECT_HOUSE = 'RESET_SELECT_HOUSE';

export const SELECT_HOUSE_DETAIL_REQUEST = 'SELECT_HOUSE_DETAIL_REQUEST';
export const SELECT_HOUSE_DETAIL_SUCCESS = 'SELECT_HOUSE_DETAIL_SUCCESS';
export const SELECT_HOUSE_DETAIL_FAILURE = 'SELECT_HOUSE_DETAIL_FAILURE';

export const INSERT_AGENT_REQUEST = 'INSERT_AGENT_REQUEST';
export const INSERT_AGENT_SUCCESS = 'INSERT_AGENT_SUCCESS';
export const INSERT_AGENT_FAILURE = 'INSERT_AGENT_FAILURE';

export const DELETE_AGENT_REQUEST = 'DELETE_AGENT_REQUEST';
export const DELETE_AGENT_SUCCESS = 'DELETE_AGENT_SUCCESS';
export const DELETE_AGENT_FAILURE = 'DELETE_AGENT_FAILURE';

export const UPDATE_AGENT_REQUEST = 'UPDATE_AGENT_REQUEST';
export const UPDATE_AGENT_SUCCESS = 'UPDATE_AGENT_SUCCESS';
export const UPDATE_AGENT_FAILURE = 'UPDATE_AGENT_FAILURE';

export const SELECT_AGENT_REQUEST = 'SELECT_AGENT_REQUEST';
export const SELECT_AGENT_SUCCESS = 'SELECT_AGENT_SUCCESS';
export const SELECT_AGENT_FAILURE = 'SELECT_AGENT_FAILURE';
export const INSERT_AGENT_REPLACE = 'INSERT_AGENT_REPLACE';
export const DELETE_AGENT_REPLACE = 'DELETE_AGENT_REPLACE';
export const UPDATE_AGENT_REPLACE = 'UPDATE_AGENT_REPLACE';

export const SELECT_AGENT_DETAIL_REQUEST = 'SELECT_AGENT_DETAIL_REQUEST';
export const SELECT_AGENT_DETAIL_SUCCESS = 'SELECT_AGENT_DETAIL_SUCCESS';
export const SELECT_AGENT_DETAIL_FAILURE = 'SELECT_AGENT_DETAIL_FAILURE';

export const SELECT_INDEX_REQUEST = 'SELECT_INDEX_REQUEST';
export const SELECT_INDEX_SUCCESS = 'SELECT_INDEX_SUCCESS';
export const SELECT_INDEX_FAILURE = 'SELECT_INDEX_FAILURE';
export const UPDATE_INDEX_REPLACE = 'UPDATE_INDEX_REPLACE';
