export const SELECT_LOGIN_REQUEST = 'SELECT_LOGIN_REQUEST';
export const SELECT_LOGIN_SUCCESS = 'SELECT_LOGIN_SUCCESS';
export const SELECT_LOGIN_FAILURE = 'SELECT_LOGIN_FAILURE';

export const INSERT_HOUSE_REQUEST = 'INSERT_HOUSE_REQUEST';
export const INSERT_HOUSE_SUCCESS = 'INSERT_HOUSE_SUCCESS';
export const INSERT_HOUSE_FAILURE = 'INSERT_HOUSE_FAILURE';

export const DELETE_HOUSE_REQUEST = 'DELETE_HOUSE_REQUEST';
export const DELETE_HOUSE_SUCCESS = 'DELETE_HOUSE_SUCCESS';
export const DELETE_HOUSE_FAILURE = 'DELETE_HOUSE_FAILURE';

export const UPDATE_HOUSE_REQUEST = 'UPDATE_HOUSE_REQUEST';
export const UPDATE_HOUSE_SUCCESS = 'UPDATE_HOUSE_SUCCESS';
export const UPDATE_HOUSE_FAILURE = 'UPDATE_HOUSE_FAILURE';

export const SELECT_HOUSE_REQUEST = 'SELECT_HOUSE_REQUEST';
export const SELECT_HOUSE_SUCCESS = 'SELECT_HOUSE_SUCCESS';
export const SELECT_HOUSE_FAILURE = 'SELECT_HOUSE_FAILURE';
export const RESET_HOUSE_STATE = 'RESET_HOUSE_STATE';

export const SELECT_HOUSE_DETAIL_REQUEST = 'SELECT_HOUSE_DETAIL_REQUEST';
export const SELECT_HOUSE_DETAIL_SUCCESS = 'SELECT_HOUSE_DETAIL_SUCCESS';
export const SELECT_HOUSE_DETAIL_FAILURE = 'SELECT_HOUSE_DETAIL_FAILURE';
